-- ============================================================
-- Taller Mecanico Mikes Ltda.
-- Semana 8 - Modelamiento de Bases de Datos
-- Autor: Fuad Onate
-- Institucion: DuocUC - Analista Programador Computacional
-- ============================================================

-- ============================================================
-- CASO 1: IMPLEMENTACION DEL MODELO (DDL)
-- Creacion de tablas en orden de dependencia
-- ============================================================

-- Tabla PAIS (identity inicia en 9, incrementa en 3)
CREATE TABLE pais (
    id_pais     NUMBER(3) GENERATED BY DEFAULT AS IDENTITY (START WITH 9 INCREMENT BY 3),
    nom_pais    VARCHAR2(30) NOT NULL
);

ALTER TABLE pais ADD CONSTRAINT pais_pk PRIMARY KEY (id_pais);

-- Tabla CIUDAD
CREATE TABLE ciudad (
    id_ciudad   NUMBER(3) NOT NULL,
    nom_ciudad  VARCHAR2(30) NOT NULL,
    cod_pais    NUMBER(3) NOT NULL
);

ALTER TABLE ciudad ADD CONSTRAINT ciudad_pk PRIMARY KEY (id_ciudad);
ALTER TABLE ciudad ADD CONSTRAINT ciudad_fk_pais FOREIGN KEY (cod_pais) REFERENCES pais(id_pais);

-- Tabla SUCURSAL
CREATE TABLE sucursal (
    id_sucursal     CHAR(3) NOT NULL,
    nom_sucursal    VARCHAR2(20) NOT NULL,
    calle           VARCHAR2(20) NOT NULL,
    num_calle       NUMBER(4) NOT NULL,
    cod_ciudad      NUMBER(3) NOT NULL
);

ALTER TABLE sucursal ADD CONSTRAINT sucursal_pk PRIMARY KEY (id_sucursal);
ALTER TABLE sucursal ADD CONSTRAINT sucursal_fk_ciudad FOREIGN KEY (cod_ciudad) REFERENCES ciudad(id_ciudad);

-- Tabla MECANICO (identity inicia en 460, incrementa en 7)
CREATE TABLE mecanico (
    cod_mecanico    NUMBER(5) GENERATED BY DEFAULT AS IDENTITY (START WITH 460 INCREMENT BY 7),
    pnombre         VARCHAR2(20) NOT NULL,
    snombre         VARCHAR2(20) NOT NULL,
    apaterno        VARCHAR2(20) NOT NULL,
    amaterno        VARCHAR2(20) NOT NULL,
    bono_jefatura   NUMBER(10),
    sueldo          NUMBER(10) NOT NULL,
    monto_impuestos NUMBER(10) NOT NULL,
    cod_supervisor  NUMBER(5)
);

ALTER TABLE mecanico ADD CONSTRAINT mecanico_pk PRIMARY KEY (cod_mecanico);
ALTER TABLE mecanico ADD CONSTRAINT mecanico_fk_mecanico FOREIGN KEY (cod_supervisor) REFERENCES mecanico(cod_mecanico);

-- Tabla CLIENTE
CREATE TABLE cliente (
    rut         NUMBER(8) NOT NULL,
    dv          CHAR(1) NOT NULL,
    pnombre     VARCHAR2(20) NOT NULL,
    snombre     VARCHAR2(20),
    apaterno    VARCHAR2(20) NOT NULL,
    amaterno    VARCHAR2(20) NOT NULL,
    telefono    VARCHAR2(12),
    email       VARCHAR2(40),
    tipo_cli    CHAR(1) NOT NULL
);

ALTER TABLE cliente ADD CONSTRAINT cliente_pk PRIMARY KEY (rut);

-- Tabla ESTANDAR (subtipo de CLIENTE)
CREATE TABLE estandar (
    cl_rut              NUMBER(8) NOT NULL,
    puntaje_fidelidad   NUMBER(10) NOT NULL
);

ALTER TABLE estandar ADD CONSTRAINT normal_pk PRIMARY KEY (cl_rut);
ALTER TABLE estandar ADD CONSTRAINT normal_fk_cliente FOREIGN KEY (cl_rut) REFERENCES cliente(rut);

-- Tabla PREMIUM (subtipo de CLIENTE)
CREATE TABLE premium (
    cl_rut          NUMBER(8) NOT NULL,
    pesos_clientes  NUMBER(10) NOT NULL,
    monto_credito   NUMBER(10)
);

ALTER TABLE premium ADD CONSTRAINT premium_pk PRIMARY KEY (cl_rut);
ALTER TABLE premium ADD CONSTRAINT premium_fk_cliente FOREIGN KEY (cl_rut) REFERENCES cliente(rut);

-- Tabla MARCA
CREATE TABLE marca (
    id_marca    NUMBER(2) NOT NULL,
    descripcion VARCHAR2(20) NOT NULL
);

ALTER TABLE marca ADD CONSTRAINT marca_pk PRIMARY KEY (id_marca);

-- Tabla MODELO
CREATE TABLE modelo (
    id_modelo   NUMBER(5) NOT NULL,
    marca_id    NUMBER(2) NOT NULL,
    descripcion VARCHAR2(20) NOT NULL
);

ALTER TABLE modelo ADD CONSTRAINT modelo_pk PRIMARY KEY (id_modelo, marca_id);
ALTER TABLE modelo ADD CONSTRAINT modelo_fk_marca FOREIGN KEY (marca_id) REFERENCES marca(id_marca);

-- Tabla TIPO_AUTOMOVIL
CREATE TABLE tipo_automovil (
    id_tipo     CHAR(3) NOT NULL,
    descripcion VARCHAR2(20) NOT NULL
);

ALTER TABLE tipo_automovil ADD CONSTRAINT tipo_automovil_pk PRIMARY KEY (id_tipo);

-- Tabla AUTOMOVIL
CREATE TABLE automovil (
    patente         CHAR(8) NOT NULL,
    annio           NUMBER(4) NOT NULL,
    cant_puertas    NUMBER(1) NOT NULL,
    km              NUMBER(6) NOT NULL,
    color           VARCHAR2(30) NOT NULL,
    cod_tipo_auto   CHAR(3) NOT NULL,
    cod_modelo      NUMBER(5) NOT NULL,
    cod_marca       NUMBER(2) NOT NULL,
    cl_rut          NUMBER(8) NOT NULL
);

ALTER TABLE automovil ADD CONSTRAINT automovil_pk PRIMARY KEY (patente);
ALTER TABLE automovil ADD CONSTRAINT automovil_fk_cliente FOREIGN KEY (cl_rut) REFERENCES cliente(rut);
ALTER TABLE automovil ADD CONSTRAINT automovil_fk_modelo FOREIGN KEY (cod_modelo, cod_marca) REFERENCES modelo(id_modelo, marca_id);
ALTER TABLE automovil ADD CONSTRAINT automovil_fk_tipo FOREIGN KEY (cod_tipo_auto) REFERENCES tipo_automovil(id_tipo);

-- Tabla MANTENCION
CREATE TABLE mantencion (
    num_mantencion  NUMBER(4) NOT NULL,
    cod_sucursal    CHAR(3) NOT NULL,
    fecha_ingreso   DATE NOT NULL,
    fecha_salida    DATE,
    patente_auto    CHAR(8),
    cod_mecanico    NUMBER(5) NOT NULL,
    costo_total     NUMBER(7),
    estado          VARCHAR2(15)
);

ALTER TABLE mantencion ADD CONSTRAINT mantencion_pk PRIMARY KEY (num_mantencion);
ALTER TABLE mantencion ADD CONSTRAINT mant_fk_automovil FOREIGN KEY (patente_auto) REFERENCES automovil(patente);
ALTER TABLE mantencion ADD CONSTRAINT mant_fk_mecanico FOREIGN KEY (cod_mecanico) REFERENCES mecanico(cod_mecanico);
ALTER TABLE mantencion ADD CONSTRAINT mant_fk_sucursal FOREIGN KEY (cod_sucursal) REFERENCES sucursal(id_sucursal);

-- Tabla SERVICIO
CREATE TABLE servicio (
    id_servicio NUMBER(3) NOT NULL,
    descripcion VARCHAR2(100) NOT NULL,
    costo       NUMBER(7) NOT NULL
);

ALTER TABLE servicio ADD CONSTRAINT servicio_pk PRIMARY KEY (id_servicio);

-- Tabla DETALLE_SERVICIO
CREATE TABLE detalle_servicio (
    mantencion_num  NUMBER(4) NOT NULL,
    cod_servicio    NUMBER(3) NOT NULL,
    descuento_serv  NUMBER(4,3),
    cantidad        NUMBER(3) NOT NULL
);

ALTER TABLE detalle_servicio ADD CONSTRAINT detalle_servicio_pk PRIMARY KEY (mantencion_num, cod_servicio);
ALTER TABLE detalle_servicio ADD CONSTRAINT det_serv_fk_mantencion FOREIGN KEY (mantencion_num) REFERENCES mantencion(num_mantencion);
ALTER TABLE detalle_servicio ADD CONSTRAINT det_serv_fk_servicio FOREIGN KEY (cod_servicio) REFERENCES servicio(id_servicio);


-- ============================================================
-- CASO 2: MODIFICACION DEL MODELO (ALTER TABLE)
-- Reglas de negocio adicionales
-- ============================================================

-- 2.1 Eliminar columna costo_total de MANTENCION (atributo derivado)
ALTER TABLE mantencion DROP COLUMN costo_total;

-- 2.2 Cambiar PK de MANTENCION a compuesta (num_mantencion, cod_sucursal)
--     y ajustar FK en DETALLE_SERVICIO
ALTER TABLE detalle_servicio DROP CONSTRAINT det_serv_fk_mantencion;
ALTER TABLE mantencion DROP CONSTRAINT mantencion_pk;
ALTER TABLE mantencion ADD CONSTRAINT mantencion_pk PRIMARY KEY (num_mantencion, cod_sucursal);

ALTER TABLE detalle_servicio ADD cod_sucursal CHAR(3);
ALTER TABLE detalle_servicio ADD CONSTRAINT det_serv_fk_mantencion 
    FOREIGN KEY (mantencion_num, cod_sucursal) REFERENCES mantencion(num_mantencion, cod_sucursal);

-- 2.3 UNIQUE en email de CLIENTE
ALTER TABLE cliente ADD CONSTRAINT cliente_un_email UNIQUE (email);

-- 2.4 CHECK en dv de CLIENTE
ALTER TABLE cliente ADD CONSTRAINT cliente_ck_dv 
    CHECK (dv IN ('0','1','2','3','4','5','6','7','8','9','K'));

-- 2.5 CHECK en sueldo de MECANICO (minimo $510.000)
ALTER TABLE mecanico ADD CONSTRAINT mecanico_ck_sueldo CHECK (sueldo >= 510000);

-- 2.6 CHECK en estado de MANTENCION
ALTER TABLE mantencion ADD CONSTRAINT mantencion_ck_estado 
    CHECK (estado IN ('Reserva', 'Ingresado', 'Entregado', 'Anulado'));


-- ============================================================
-- CASO 3: POBLAMIENTO DEL MODELO (DML)
-- Insercion de datos en orden de dependencia
-- ============================================================

-- Secuencia para CIUDAD (inicia en 165, incrementa en 5)
CREATE SEQUENCE seq_ciudad START WITH 165 INCREMENT BY 5;

-- Secuencia para SERVICIO (inicia en 400, incrementa en 2)
CREATE SEQUENCE seq_servicio START WITH 400 INCREMENT BY 2;

-- Insertar PAIS (usa identity: 9, 12, 15)
INSERT INTO pais (nom_pais) VALUES ('Chile');
INSERT INTO pais (nom_pais) VALUES ('Peru');
INSERT INTO pais (nom_pais) VALUES ('Colombia');

-- Insertar CIUDAD (usa secuencia: 165, 170, 175)
INSERT INTO ciudad VALUES (seq_ciudad.NEXTVAL, 'Santiago', 9);
INSERT INTO ciudad VALUES (seq_ciudad.NEXTVAL, 'Lima', 12);
INSERT INTO ciudad VALUES (seq_ciudad.NEXTVAL, 'Bogota', 15);

-- Insertar SUCURSAL
INSERT INTO sucursal VALUES ('S01', 'Providencia', 'Av. A. Varas', 234, 165);
INSERT INTO sucursal VALUES ('S02', 'Las 4 esquinas', 'Av. Latina', 669, 170);
INSERT INTO sucursal VALUES ('S03', 'El Cafetero', 'Av. El Faro', 900, 175);

-- Insertar MECANICO (usa identity: 460, 467, 474, ...)
-- Primero los que no tienen supervisor
INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Jorge', 'Pablo', 'Soto', 'Sierpe', 5400000, 2759000, 223580, NULL);

INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Pedro', 'Jose', 'Manriquez', 'Corral', NULL, 759000, 23980, NULL);

-- Luego los que referencian cod_supervisor = 460 o 474
INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Sandra', 'Josefa', 'Letelier', 'S.', 0, 659000, 22358, 460);

INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Felipe', 'M.', 'Vidal', 'A.', NULL, 759000, 23580, 460);

INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Jose', 'Miguel', 'Troncoso', 'B.', NULL, 659000, 44580, 474);

INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Juan', 'Pablo', 'Sanchez', 'R.', NULL, 859000, 23380, 474);

INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Carlos', 'Felipe', 'Soto', 'J.', 0, 597000, 23580, 474);

INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Alberto', 'P.', 'Cerda', 'Ramirez', NULL, 559000, 22380, 460);

INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Alejandra', 'Gabriela', 'Infanti', 'R.', NULL, 659000, 22380, 460);

INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Roberto', 'Patricio', 'Gutierrez', 'Sosa', NULL, 859000, 22380, 460);

-- Insertar SERVICIO (usa secuencia: 400, 402, 404, 406)
INSERT INTO servicio VALUES (seq_servicio.NEXTVAL, 'Cambio Luces', 45000);
INSERT INTO servicio VALUES (seq_servicio.NEXTVAL, 'Desabolladura', 67000);
INSERT INTO servicio VALUES (seq_servicio.NEXTVAL, 'Revision Frenos', 30000);
INSERT INTO servicio VALUES (seq_servicio.NEXTVAL, 'Cambio Puerta Trasera', 50000);

-- Insertar MANTENCION
INSERT INTO mantencion (num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida, patente_auto, cod_mecanico, estado)
VALUES (101, 'S01', TO_DATE('12-04-2023', 'DD-MM-YYYY'), NULL, NULL, 481, 'Reserva');

INSERT INTO mantencion (num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida, patente_auto, cod_mecanico, estado)
VALUES (102, 'S02', TO_DATE('21-02-2023', 'DD-MM-YYYY'), TO_DATE('21-02-2023', 'DD-MM-YYYY'), NULL, 502, 'Entregado');

INSERT INTO mantencion (num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida, patente_auto, cod_mecanico, estado)
VALUES (103, 'S02', TO_DATE('09-10-2023', 'DD-MM-YYYY'), NULL, NULL, 502, 'Anulado');

INSERT INTO mantencion (num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida, patente_auto, cod_mecanico, estado)
VALUES (104, 'S03', TO_DATE('11-08-2023', 'DD-MM-YYYY'), TO_DATE('18-08-2023', 'DD-MM-YYYY'), NULL, 509, 'Entregado');

INSERT INTO mantencion (num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida, patente_auto, cod_mecanico, estado)
VALUES (105, 'S03', TO_DATE('03-12-2023', 'DD-MM-YYYY'), NULL, NULL, 509, 'Ingresado');

-- Confirmar cambios
COMMIT;


-- ============================================================
-- CASO 4: RECUPERACION DE DATOS (SELECT)
-- Informes estadisticos
-- ============================================================

-- INFORME 1: Simulacion de rebaja de impuestos a mecanicos
-- Mecanicos con bono_jefatura nulo y monto_impuestos < 40000
-- Impuesto rebajado = 80% del impuesto actual
-- Ordenado por impuesto actual DESC, apellido paterno ASC
SELECT cod_mecanico AS "ID MECANICO",
       pnombre || ' ' || apaterno AS "NOMBRE MECANICO",
       sueldo AS "SALARIO",
       monto_impuestos AS "IMPUESTO ACTUAL",
       monto_impuestos * 0.8 AS "IMPUESTO REBAJADO",
       sueldo - (monto_impuestos * 0.8) AS "SUELDO CON REBAJA IMPUESTOS"
FROM mecanico
WHERE bono_jefatura IS NULL
  AND monto_impuestos < 40000
ORDER BY monto_impuestos DESC, apaterno ASC;


-- INFORME 2: Ajuste salarial del 5%
-- Mecanicos con sueldo entre 600000 y 900000 o sin supervisor
-- Ordenado por sueldo actual ASC, nombre completo DESC
SELECT cod_mecanico AS "IDENTIFICADOR",
       pnombre || ' ' || snombre || ' ' || apaterno AS "MECANICO",
       sueldo AS "SALARIO ACTUAL",
       sueldo * 0.05 AS "AJUSTE",
       sueldo + (sueldo * 0.05) AS "SUELDO_REAJUSTADO"
FROM mecanico
WHERE (sueldo BETWEEN 600000 AND 900000)
   OR (cod_supervisor IS NULL)
ORDER BY sueldo ASC, pnombre || ' ' || snombre || ' ' || apaterno DESC;
